### ISSUE TITLE
Query Github for Issues

### ISSUE THREAD

**Issue by fadyibrahim** [strangestar/BugHunt4806#14]

**Comment by strangestar** [comment]
Users should be able to add Bugs to a Hunt by using github.
They should be able to point to a repository, do any necessary authentication, and have all open issues from that project added as Bugs. 
Ideally, there would be checkboxes or something so the user could then choose which Bugs they actually want to add to the Hunt.

**Comment by fadyibrahim** [comment]
Query works. Now working on parsing the json object.
